# Generated by Django 4.1.1 on 2022-09-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.EmailField(max_length=254, unique=True)),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                (
                    "short_url",
                    models.EmailField(blank=True, max_length=254, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
