# Generated by Django 4.1.1 on 2022-09-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="url",
            name="short_url",
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="url_hash",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
