# Generated by Django 4.1.1 on 2022-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_url_clicks_alter_url_short_url_alter_url_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="time_click",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
